spring:
  application:
    name: socialcoffee

  datasource:
    url: jdbc:postgresql://localhost:5432/socialcoffee
    username: postgres
    password: 1

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

  ai:
    openai:
      api-key: ${OPEN_API_KEY:default}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct

  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB

  redis:
    prefix-key: socialcoffee

  cache:
    type: simple

security:
  jwt:
    token:
      secret-key: ${TOKEN_SECRET_KEY:secret-key}
      expire-length-in-seconds: 86400
    refresh-token:
      expire-length-in-seconds: 86400

cors:
  mapping:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

postgres:
  transaction:
    manager: postgresTransactionManager

neo4j:
  transaction:
    manager: neo4jTransactionManager

oauth2:
  client:
    registration:
      google:
        userinfo-endpoint: https://www.googleapis.com/oauth2/v3/userinfo
        client-id: ${GOOGLE_CLIENT_ID:client-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}

app:
  security:
    user-facebook-api: https://graph.facebook.com/v19.0/me?fields=id%2Cname%2Cemail%2Cbirthday%2Cgender%2Cpicture&access_token=
  posts:
    max-length-comment: 2000
