DROP DATABASE socialcoffee;
create extension postgis;
create extension pgvector;
DELETE FROM coffee_shop_ambiance;
DELETE FROM coffee_shop_amenity;
DELETE FROM coffee_shop_capacity;
DELETE FROM coffee_shop_dress_code;
DELETE FROM coffee_shop_entertainment;
DELETE FROM coffee_shop_parking;
DELETE FROM coffee_shop_price;
DELETE FROM coffee_shop_service;
DELETE FROM coffee_shop_space;
DELETE FROM coffee_shop_specialty;
DELETE FROM coffee_shop_visit_time;


CREATE DATABASE IF NOT EXISTS socialcoffee;

CREATE TABLE IF NOT EXISTS address
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_map_url VARCHAR(255),
    province       VARCHAR(255),
    district       VARCHAR(255),
    ward           VARCHAR(255),
    longitude      DOUBLE PRECISION                        NOT NULL,
    latitude       DOUBLE PRECISION                        NOT NULL,
	location       geography(POINT, 4326)
    CONSTRAINT pk_address PRIMARY KEY (id)
);
CREATE INDEX idx_address_location ON address USING GIST(location);

CREATE TABLE IF NOT EXISTS ambiances
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_ambiances PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS purposes
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_purposes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS amenities
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_amenities PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS capacities
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_capacities PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dress_code
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_dress_code PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS entertainment
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_entertainment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url           VARCHAR(255),
    thumbnail_url VARCHAR(255),
    width         DOUBLE PRECISION NOT NULL,
    height        DOUBLE PRECISION NOT NULL,
    size          DOUBLE PRECISION NOT NULL,
	status        VARCHAR(20) NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS parking;
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_parking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS prices
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_prices PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS services
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_services PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS spaces
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_spaces PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS specialties
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS visit_time
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_visit_time PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_ambiance
(
    ambiance_id    BIGINT NOT NULL,
    coffee_shop_id BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_ambiance PRIMARY KEY (ambiance_id, coffee_shop_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_purpose
(
    purpose_id    BIGINT NOT NULL,
    coffee_shop_id BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_purpose PRIMARY KEY (purpose_id, coffee_shop_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_amenity
(
    amenity_id     BIGINT NOT NULL,
    coffee_shop_id BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_amenity PRIMARY KEY (amenity_id, coffee_shop_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_capacity
(
    capacity_id    BIGINT NOT NULL,
    coffee_shop_id BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_capacity PRIMARY KEY (capacity_id, coffee_shop_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_category
(
    category_id    BIGINT NOT NULL,
    coffee_shop_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS coffee_shop_dress_code
(
    coffee_shop_id BIGINT NOT NULL,
    dress_code_id  BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_dress_code PRIMARY KEY (coffee_shop_id, dress_code_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_entertainment
(
    coffee_shop_id   BIGINT NOT NULL,
    entertainment_id BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_entertainment PRIMARY KEY (coffee_shop_id, entertainment_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_feature
(
    coffee_shop_id BIGINT NOT NULL,
    feature_id     BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_feature PRIMARY KEY (coffee_shop_id, feature_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_parking
(
    coffee_shop_id BIGINT NOT NULL,
    parking_id     BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_parking PRIMARY KEY (coffee_shop_id, parking_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_price
(
    coffee_shop_id BIGINT NOT NULL,
    price_id       BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_price PRIMARY KEY (coffee_shop_id, price_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_service
(
    coffee_shop_id BIGINT NOT NULL,
    service_id     BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_service PRIMARY KEY (coffee_shop_id, service_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_space
(
    coffee_shop_id BIGINT NOT NULL,
    space_id       BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_space PRIMARY KEY (coffee_shop_id, space_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_specialty
(
    coffee_shop_id BIGINT NOT NULL,
    specialty_id   BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_specialty PRIMARY KEY (coffee_shop_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS coffee_shop_visit_time
(
    coffee_shop_id BIGINT NOT NULL,
    visit_time_id  BIGINT NOT NULL,
    CONSTRAINT pk_coffee_shop_visit_time PRIMARY KEY (coffee_shop_id, visit_time_id)
);

CREATE TABLE IF NOT EXISTS coffee_shops
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255),
    cover_photo           VARCHAR(255),
    phone_number          VARCHAR(255),
    web_address           VARCHAR(255),
    menu_web_address      VARCHAR(255),
	status				  VARCHAR(20),
    addition_info         VARCHAR(255),
    open_hour             BIGINT,
    close_hour            BIGINT,
    address_id       		BIGINT,
    description           TEXT,
	-- embedding_description_id BIGINT,
	created_by       BIGINT,
    CONSTRAINT pk_coffee_shops PRIMARY KEY (id)
);

CREATE TABLE coffee_shop_mood
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mood       VARCHAR(255),
    shop_id    BIGINT,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_coffee_shop_mood PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS description_embedding
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description_embedding VECTOR(384),
    CONSTRAINT pk_description_embedding PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS coffee_shops_gallery_photos
(
    coffee_shop_id    BIGINT NOT NULL,
    gallery_photos_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS users_likes
(
    coffee_shop_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    CONSTRAINT pk_users_likes PRIMARY KEY (coffee_shop_id, user_id)
);
CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_name      VARCHAR(255),
    username          VARCHAR(255),
    name              VARCHAR(255),
    email             VARCHAR(255),
    password          VARCHAR(255),
    phone             VARCHAR(255),
    dob               date,
    gender            VARCHAR(255),
    address_id        BIGINT,
    bio               VARCHAR(255),
    coffee_preference TEXT,
	embedding_description_id BIGINT,
    status            VARCHAR(255),
    profile_photo     VARCHAR(255),
    background_photo     TEXT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    last_login        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE user_settings
(
    id      BIGINT NOT NULL,
    setting VARCHAR(255),
    CONSTRAINT pk_user_settings PRIMARY KEY (id)
);

CREATE TABLE users_collections
(
    user_id        VARCHAR(255) NOT NULL,
    collections_id BIGINT       NOT NULL
);

CREATE TABLE users_roles
(
    role_id BIGINT       NOT NULL,
    user_id VARCHAR(255) NOT NULL
);

CREATE TABLE user_auth_connection
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    auth_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_auth_connection PRIMARY KEY (id)
);

CREATE TABLE user_follows
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    follower_id BIGINT NOT NULL,
    followee_id BIGINT NOT NULL,
    CONSTRAINT pk_user_follows PRIMARY KEY (follower_id, followee_id)
);

CREATE INDEX idx_followee_id ON user_follows (followee_id);

CREATE INDEX idx_follower_id ON user_follows (follower_id);

CREATE TABLE auth_providers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_auth_providers PRIMARY KEY (id)
);

CREATE TABLE collections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
	cover_url   TEXT,
    user_id     BIGINT,
    CONSTRAINT pk_collections PRIMARY KEY (id)
);


CREATE TABLE collections_coffee_shops
(
    collection_id   BIGINT NOT NULL,
    coffee_shops_id BIGINT NOT NULL
);

CREATE TABLE reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating         INTEGER,
    comment        TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(20),
    user_id        BIGINT,
    coffee_shop_id BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);
CREATE TABLE reviews_images
(
    review_id BIGINT NOT NULL,
    images_id BIGINT NOT NULL
);

CREATE TABLE review_reactions
(
    type       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    review_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_review_reactions PRIMARY KEY (review_id, user_id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    status     VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE shop_users
(
    type        VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    approved_at TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    user_id     BIGINT NOT NULL,
    shop_id     BIGINT NOT NULL,
    CONSTRAINT pk_shop_users PRIMARY KEY (user_id, shop_id)
);

CREATE TABLE coffee_shop_contributions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    contribution    TEXT,
    review_comments VARCHAR(255),
    type            VARCHAR(255),
    status          VARCHAR(255),
    submitted_by    BIGINT,
    reviewed_by     BIGINT,
    coffee_shop_id  BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_coffee_shop_contributions PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    message    VARCHAR(255),
	 status    VARCHAR(255),
    type       VARCHAR(255),
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);